app/__init__.py
from flask import Flask, session
from config import config  # --> the second config is the dict that we have defined
from flask_login import LoginManager
import datetime

login_manager = LoginManager()
login_manager.login_view = 'main.login'
login_manager.login_message = 'Please login to your account'


def time_to(deadline, diff):
    _delay_string = None
    if diff == "Nothing":
        _delay_string = "An error happened"
        return _delay_string

    input_time = datetime.datetime.strptime(deadline, '%Y-%m-%d %H:%M:%S')
    now = datetime.datetime.now()
    delta = (input_time - now).total_seconds()
    # Add the difference of dateTime between server and user
    delta += diff

    delta_minute = int(delta / 60)
    delta_hour = int(delta / (60 * 60))
    delta_day = int(delta / (60 * 60 * 24))

    if delta < 0:
        _delay_string = "Overdue"

    elif delta < 60:
        _delay_string = "less than a minute remaining"

    elif delta_minute < 60:
        if delta_minute == 1:
            _delay_string = "1 minute remaining"
        else:
            _delay_string = "{} minutes remaining".format(delta_minute)

    elif delta_hour < 24:
        if delta_hour == 1:
            _delay_string = "1 hour remaining"
        else:
            _delay_string = "{} hours remaining".format(delta_hour)

    elif delta_day < 50:
        if delta_day == 1:
            _delay_string = "1 day remaining"
        else:
            _delay_string = "{} days remaining".format(delta_day)
    else:
        _delay_string = "long time remaining"

    return _delay_string


def create_app(config_name):
    app = Flask(__name__)
    app.config.from_object(config[config_name])
    config[config_name].init_app(app)
    login_manager.init_app(app)

    # custom functions
    app.jinja_env.globals.update(time_to=time_to)

    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)
    return app

app/main/__init__.py
from flask import Blueprint

main = Blueprint('main' , __name__)
# the following line is 100% important
# if you don't write this line, the app doesn't work:
from . import views

app/main/views.py
import datetime

from flask import flash
from flask import render_template, redirect, url_for
from flask import request, session
from flask_login import login_required, login_user, logout_user, current_user

from . import main
from ..db_work import database
from ..user import load_user

EMOJIE_PURE_LIST = ["#128640", "#128170", "#128163", "#128218", "#128181", "#9989", "#9940", "#9888", "#8987",
                    "#9760", "#10002", "#128705", "#128680", "#128679", "#128564",
                    "#128556", "#128557", "#128548", "#128515"]


@main.route('/')
@login_required
def index():
    user_id = current_user.get_id()
    task_list = database().get_all_user_tasks(user_id)
    connection = database().get_connection()
    result = connection.execute("SELECT diff FROM user WHERE user_id = ?",
                       [user_id]).fetchone()
    connection.close()
    if result is not None:
        return render_template('index.html', task_list=task_list, diff=result['diff'])
    else:
        return render_template('index.html', task_list=task_list, diff="Nothing")


@main.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == "POST":
        ticket_number = request.form.get('ticket_number')
        user_password = request.form.get('user_password')
        # The following part is really important, But why?
        # The server current time and the user current time maybe different from each other
        # Because they may exist in different time zones
        # So Here we are getting the user current time and calculating the difference between user current time and 
        # server current time.
        # each time we are calculating the remaining time to a deadline we should add this difference...:)
        user_dateTime = request.form.get('current_dateTime')
        user_dateTime = user_dateTime.replace('T', ' ') + ':00'

        is_valid = database().check_password(ticket_number, user_password)
        if is_valid:
            user_obj = load_user(ticket_number)
            login_user(user_obj, remember=True)

            # diff_dateTime is the difference between server and user
            user_dateTime = datetime.datetime.strptime(user_dateTime, '%Y-%m-%d %H:%M:%S')
            server_dateTime = datetime.datetime.now()
            diff = (server_dateTime - user_dateTime).total_seconds()
            connection = database().get_connection()
            connection.execute("UPDATE user SET diff = ? WHERE user_id = ?",
                               (diff, ticket_number))
            connection.commit()
            connection.close()

            return redirect(url_for('main.index'))
        else:
            flash('Incorrect ticket or password')
            return redirect(url_for('main.login'))

    return render_template('login.html')


@main.route('/logout')
@login_required
def logout():
    logout_user()
    flash('logged out')
    return redirect(url_for('main.index'))


@main.route('/signup', methods=['GET', 'POST'])
def signup():
    if request.method == "POST":
        ticket_number = request.form.get('ticket_number')
        invite_code = request.form.get('invite_code')
        user_password = request.form.get('user_password')
        user_dateTime = request.form.get('current_dateTime')

        status = database().check_new_user(ticket_number, invite_code)
        if status == -2:
            flash("Not found!")
            return redirect(url_for('main.signup'))

        elif status == 1:
            successful_add = database().add_new_user(ticket_number, user_password, user_dateTime)
            if successful_add:
                flash("User was successfully added")
                user_obj = load_user(ticket_number)
                login_user(user_obj, remember=True)
                return redirect(url_for('main.index'))

        elif status == 0:
            flash("This invite code is expired")
            return redirect(url_for('main.signup'))

        elif status == -1:
            flash("Invalid invite_code")
            return redirect(url_for('main.signup'))
    return render_template('signup.html')


@main.route('/add', methods=['GET', 'POST'])
@login_required
def add_task():
    if request.method == "POST":
        task_name = request.form['task_name']
        task_desc = request.form['task_desc']
        task_emoji = request.form['task_emoji']
        task_color = int(request.form['task_color'])
        deadline_isactive = request.form.getlist('deadline_isactive')
        task_deadline = request.form['task_deadline']

        if len(task_name) > 25 or len(task_desc) > 50:
            flash("Error in adding the task")
            return redirect(url_for('main.add_task'))

        add_status = False
        is_active = 0
        if 'on' in deadline_isactive:
            is_active = 1
            print("$ on" * 20)
            task_deadline = task_deadline.replace('T', ' ') + ':00'
            deadline_time = datetime.datetime.strptime(task_deadline, '%Y-%m-%d %H:%M:%S')
            now = datetime.datetime.now()
            if (deadline_time - now).total_seconds() < 0:
                flash("Task deadline couldn't be before the the current time!")
                return redirect(url_for('main.add_task'))

        add_status = database().add_task(task_name, task_desc, task_emoji, task_color, is_active,
                                         task_deadline, current_user.get_id())
        if add_status:
            flash("Task added to the board")
            return redirect(url_for('main.index'))
        else:
            flash("Error in task add")
            return redirect(url_for('main.add_task'))

    return render_template('add.html', emojis_pure=EMOJIE_PURE_LIST)


@main.route('/delete/<int:task_id>')
@login_required
def delete(task_id):
    if database().check_author(current_user.get_id(), task_id):
        if database().delete_task(task_id):
            flash("Task deleted")
        else:
            flash("Sorry an error happened")
    else:
        flash("Access denied!")

    return redirect(url_for('main.index'))

app/templates/add.html
{% extends "base.html" %}

{% block title %}Add task{% endblock %}
{% block menu_item %}
<a href="{{ url_for('main.index') }}" class="nav-link text-dark" style="font-size: 1.5rem;font-weight: bold;">Board</a>
<a href="{{ url_for('main.logout') }}" class="nav-link text-dark" style="font-size: 1.5rem;font-weight: bold;">Logout</a>
{% endblock %}

{% block main %}
<div class="container-fluid">
  <div class="d-flex justify-content-center">
    <div class="d-flex bg-dark col-9 text-warning justify-content-center shadow-lg" style="border-style: inset;border-radius: 40px;
      padding: 12px;border: 0px;">
        <form method="post" class="col-11">
    
          <div class="mb-3">
            <label for="task_name" class="form-label">Task name</label>
            <input type="text" class="form-control" name="task_name" id="task_name"
            placeholder="Writing the assignment" aria-describedby="name_help"
            maxlength="25" title="maximum length is 25" required>
            <div class="form-text mx-2 text-secondary" id="name_help">Using a proper name is always good</div>
          </div>

          <div class="mb-3">
            <label for="task_desc" class="form-label">Task description</label>
            <input type="text" class="form-control" name="task_desc" id="task_desc"
            placeholder="I should mail it ASAP" aria-describedby="desc_help"
            maxlength="50" title="maximum length is 50" required>
            <div class="form-text mx-2 text-secondary" id="desc_help">You can add a description here</div>
          </div>

          <div class="mb-3">
              <label for="deadline_active" class="form-label">Use a deadline ?</label>
              <br>
              <div class="form-check form-check-inline">
                <input class="form-check-input" type="radio" name="deadline_isactive" id="deadline_active" value="on"
                onchange="isActive(this.value);">
                <label class="form-check-label text-secondary" for="deadline_active">Yes</label>
              </div>
            
              <div class="form-check form-check-inline">
                <input class="form-check-input" type="radio" name="deadline_isactive" id="deadline_inactive" value="off"
                onchange="isActive(this.value);" checked>
                <label class="form-check-label text-secondary" for="deadline_inactive">No</label>
              </div>
            <div id="gp_deadline" class="mt-1" hidden>
              <input type="datetime-local" class="w-75 rounded p-1 mt-1 shadow-lg bg-dark bg-gradient text-secondary"
              id="task_deadline" name="task_deadline" aria-describedby="deadline_help">
              <div class="form-text mx-2 text-secondary" id="deadline_help">You can add a deadline here</div>
            </div>
          </div>

          <div class="mb-3">
            <label for="task_emoji">Task emoji</label>
            <select class="form-select mt-2" name="task_emoji" id="task_emoji" aria-describedby="emoji-help">
              {% for emoji_pure in emojis_pure%}
              <option value="{{emoji_pure}}">&{{emoji_pure}};</option>
              {% endfor %}
            </select>
            <div class="form-text mx-2 text-secondary" id="emoji_help">Customize it with an emoji</div>
          </div>
          
          <div class="mb-3">
            <div class="col">
              <label for="color_range" class="form-label">Task color</label>
              <label class="form-text mx-2 text-secondary">Use colors for having a better sense about task</label>
            </div>
            <input class="form-range" type="range" id="color_range" name="task_color" min="0" value="0" max="4" onchange="updateColor(this.value);">
            <div class="mx-2">
              <h1 class="text-secondary text-center"><span id="color_label" class="text-warning">Task color</span></h1>
            </div>
        
            <script>
              function updateColor(val) {
                if(val == 0){
                  document.getElementById('color_label').className="text-warning"; 
                }
                else if(val == 1){
                  document.getElementById('color_label').className="text-danger"; 
                }
                else if(val == 2){
                  document.getElementById('color_label').className="text-primary"; 
                }
                else if(val == 3){
                  document.getElementById('color_label').className="text-success"; 
                }
                else if(val == 4){
                  document.getElementById('color_label').className="text-light"; 
                }
              };

              function isActive(val){
                if(val == 'on'){
                  document.getElementById('gp_deadline').removeAttribute("hidden");
                  document.getElementById('task_deadline').setAttribute("required", true)
                }
                else if(val == 'off'){
                  document.getElementById('gp_deadline').setAttribute("hidden", true);
                  document.getElementById('task_deadline').removeAttribute("required");
                }
              };
              </script>
          </div>

          <div class="d-flex justify-content-center">
            <button type="submit" class="btn btn-warning col-6" style="font-size:large;font-weight: bold;">Add !</button>
          </div>      
      
        </form>
    </div>
  </div>
</div>
<br><br><br><br>
{% endblock %}

app/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="icon" href="static/favicon.png" type="image/icon type">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

    <title>{% block title %}{% endblock %}</title>
  </head>
  <body class="bg-dark">
    <div class="container">
      <div class="mt-1 d-flex bg-warning rounded justify-content-center shadow-lg">
        {% block menu_item %}
        {% endblock %}
      </div>
      <br>
      {% with messages = get_flashed_messages() %}
        {% if messages[-1] %}
            <div class="row w-50" style="margin: auto;width: 30%;">
              <div class="alert alert-secondary dismissible fade show">
                <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
                {{ messages[-1] }}
              </div>
            </div>
        {% endif %}
      {% endwith %}
      <br>
      {% block main %}{% endblock %}
      <footer class="text-lg-start fixed-bottom" style="background-color: rgba(0, 0, 0, 0.418);">
        <!-- Copyright -->
        <div class="p-3 text-secondary">
          Made with ❤️ by 
          <a class="text-light" target="_blank" style="text-decoration: none;" href="https://github.com/alidr79">A-Derakhshesh</a>
        </div>
        <!-- Copyright -->
      </footer>
    </div>

    
  </body>
</html>

app/templates/index.html
{% extends "base.html" %}

{% block title %}Board{% endblock %}
{% block menu_item %}
<a href="{{ url_for('main.add_task') }}" class="nav-link text-dark" style="font-size: 1.5rem;font-weight: bold;">Add task</a>
<a href="{{ url_for('main.logout') }}" class="nav-link text-dark" style="font-size: 1.5rem;font-weight: bold;">Logout</a>
{% endblock %}


{% block main %}
<div class="d-flex flex-wrap rounded p-2">
  {% if not task_list[0] %}
  <h1 class="text-light">There is nothing to do</h1>

  {% else %}
    {% for task in task_list %}
      <div class="card flex-fill me-1 ms-1 mb-2 bg-dark shadow-lg">
        <div class="card-body">
          {% if task['task_color']==0 %}
            <h3 class="card-title text-warning">&{{ task['task_emoji'] }};{{ task['task_name'] }}</h3>
          {% endif %}
          {% if task['task_color']==1 %}
            <h3 class="card-title text-danger">&{{ task['task_emoji'] }};{{ task['task_name'] }}</h3>
          {% endif %}
          {% if task['task_color']==2 %}
            <h3 class="card-title text-primary">&{{ task['task_emoji'] }};{{ task['task_name'] }}</h3>
          {% endif %}
          {% if task['task_color']==3 %}
            <h3 class="card-title text-success">&{{ task['task_emoji'] }};{{ task['task_name'] }}</h3>
          {% endif %}
          {% if task['task_color']==4 %}
            <h3 class="card-title text-light">&{{ task['task_emoji'] }};{{ task['task_name'] }}</h3>
          {% endif %}
          
          
          <p class="card-text text-secondary">{{ task['task_desc'] }}</p>
          <a href="{{ url_for('main.delete', task_id = task['task_id']) }}" class="btn btn-outline-warning">Done</a>
        </div>
        <div class="card-footer text-muted">
          {% if task['deadline_isactive'] == 1 %}
            {{ time_to(task['task_deadline'], diff) }}
          {% elif task['deadline_isactive'] == 0 %}
            Just do it
          {% endif %}
        </div>
      </div>
    {% endfor %}
  {% endif %}


</div>
<br>
<br>


{% endblock %}

app/templates/login.html
{% extends "base.html" %}

{% block title %}Login{% endblock %}
{% block menu_item %}
<a href="{{ url_for('main.index') }}" class="nav-link text-dark" style="font-size: 1.5rem;font-weight: bold;">Board</a>
<a href="{{ url_for('main.signup') }}" class="nav-link text-dark" style="font-size: 1.5rem;font-weight: bold;">Signup</a>
{% endblock %}

{% block main %}
<div class="container-fluid">
  <div class="d-flex justify-content-center">
    <div class="d-flex bg-dark col-9 text-warning justify-content-center shadow-lg" style="border-style: inset;border-radius: 40px;
      padding: 12px;border: 0px;">
        <form method="post" class="col-11">
    
          <div class="mb-3">
            <label for="ticket_number" class="form-label">Ticket number</label>
            <input type="number" class="form-control" name="ticket_number" id="ticket_number"
            placeholder="Ticket number" aria-describedby="name_help"
            maxlength="4" title="maximum length is 4" required>
            <div class="form-text mx-2 text-secondary" id="name_help">Please enter your ticket number</div>
          </div>

          <div class="mb-3">
            <label for="current_dateTime" class="form-label">Current date and time</label><br>
            <input type="datetime-local" class="w-75 rounded p-1 mt-1 shadow-lg bg-dark bg-gradient text-secondary"
            id="current_dateTime" name="current_dateTime" aria-describedby="current_dateTime_help" required>
            <div class="form-text mx-2 text-secondary" id="current_dateTime_help">Please enter your current dateTime</div>
          </div>

          <div class="mb-3">
            <label for="user_password" class="form-label">Password</label>
            <input type="password" class="form-control" name="user_password" id="user_password"
            placeholder="********" aria-describedby="desc_help"
            maxlength="16" minlength="8" title="maximum length is 16 and minimum length is 8" required>
            <div class="mt-2">
                <input type="checkbox" name="showOrHide" id="cb_showHide" class="form-check-input" onchange="show_hide();">
                <label for="cb_showHide" class="form-check-label ms-1">Show/hide</label>
            </div>          
          </div>

          <script>
            function show_hide() {
              var x = document.getElementById("user_password");
              if (x.type == "password") {
                x.type = "text";
              } else {
                  x.type = "password";
                  }
              }
          </script>

          <div class="d-flex justify-content-center">
            <button type="submit" class="btn btn-warning col-6" style="font-size:large;font-weight: bold;">Login</button>
          </div>      
      
        </form>
    </div>
  </div>
</div>
<br><br><br><br>
{% endblock %}

app/templates/signup.html
{% extends "base.html" %}

{% block title %}Signup{% endblock %}
{% block menu_item %}
<a href="{{ url_for('main.index') }}" class="nav-link text-dark" style="font-size: 1.5rem;font-weight: bold;">Board</a>
<a href="{{ url_for('main.login') }}" class="nav-link text-dark" style="font-size: 1.5rem;font-weight: bold;">Login</a>
{% endblock %}

{% block main %}
<div class="container-fluid">
  <div class="d-flex justify-content-center">
    <div class="d-flex bg-dark col-9 text-warning justify-content-center shadow-lg" style="border-style: inset;border-radius: 40px;
      padding: 12px;border: 0px;">
        <form method="post" class="col-11">
    
          <div class="mb-3">
            <label for="ticket_number" class="form-label">Ticket number</label>
            <input type="number" class="form-control" name="ticket_number" id="ticket_number"
            placeholder="Ticket number" aria-describedby="name_help"
            maxlength="4" title="maximum length is 4" required>
            <div class="form-text mx-2 text-secondary" id="name_help">Please enter your ticket number</div>
          </div>


          <div class="mb-3">
            <label for="invite_code" class="form-label">Invite code</label>
            <input type="text" class="form-control" name="invite_code" id="invite_code"
            placeholder="****" aria-describedby="name_help"
            maxlength="12" title="maximum length is 12" required>
            <div class="form-text mx-2 text-secondary" id="name_help">You should get an invite code from the admin</div>
          </div>

          <div class="mb-3">
            <label for="current_dateTime" class="form-label">Current date and time</label><br>
            <input type="datetime-local" class="w-75 rounded p-1 mt-1 shadow-lg bg-dark bg-gradient text-secondary"
            id="current_dateTime" name="current_dateTime" aria-describedby="current_dateTime_help" required>
            <div class="form-text mx-2 text-secondary" id="current_dateTime_help">Please enter your current dateTime</div>
          </div>

          <div class="mb-3">
            <label for="user_password" class="form-label" id="ada">Password</label>
            <input type="password" class="form-control" name="user_password" id="user_password"
            placeholder="********" aria-describedby="desc_help"
            maxlength="16" minlength="8" title="maximum length is 16 and minimum length is 8" required>
            <div class="form-text mx-2 text-secondary" id="desc_help">Choose a <b>strong</b> password</div>
            <input type="checkbox" name="showOrHide" id="cb_showHide" class="form-check-input" onchange="show_hide();">
            <label for="cb_showHide" class="form-check-label ms-1">Show/hide</label>          
          </div>

          <script>
            function show_hide() {
              var x = document.getElementById("user_password");
              if (x.type == "password") {
                x.type = "text";
              } else {
                  x.type = "password";
                  }
              }
          </script>

          <div class="d-flex justify-content-center">
            <button type="submit" class="btn btn-warning col-6" style="font-size:large;font-weight: bold;">Signup</button>
          </div>      
      
        </form>
    </div>
  </div>
</div>
<br><br><br><br>
{% endblock %}